repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check flow_proxy_plugin tests
        language: system
        pass_filenames: false
        always_run: true

      - id: mypy
        name: mypy
        entry: poetry run mypy flow_proxy_plugin tests
        language: system
        pass_filenames: false
        always_run: true

      - id: pylint
        name: pylint
        entry: poetry run pylint flow_proxy_plugin
        language: system
        pass_filenames: false
        always_run: true

      - id: commitizen
        name: commitizen check
        entry: poetry run cz check
        language: system
        stages: [commit-msg]
        args: [--commit-msg-file]
        pass_filenames: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
